"""Facts about Rajeev Jasti and this site, for the Bedrock chat persona.

GENERATED by scripts/generate_resume.py from content/resume.json.
Do not edit: `npm run check:resume` fails CI when this drifts from the source.

This block used to be typed by hand inside bedrock_service.DEFAULT_SYSTEM_PROMPT,
where it went stale - it described a Three.js frontend that this repository has
never contained, and predated the arcade, the predictors and the whole auth tier.
"""

KEY_INFORMATION = """\
- Current Role: Principal Data Engineer at Nicholas and Company (Nov 2022 – Present, Salt Lake City & Remote)
- Previous Role: Data Engineer at Nicholas and Company (Feb 2018 – Oct 2022)
- Specialization: Enterprise Data Engineering & OLAP modeling, OLTP Database Engines, Real-time Streaming, Cloud Migrations, Full-Stack & Generative AI Web Applications
- Backend Stack: Python 3.10+, FastAPI, PostgreSQL, SQLAlchemy ORM (asyncpg), Alembic, Amazon Bedrock, Lambda, API Gateway, Boomi, Docker, Kafka, microservices
- Cloud & Infrastructure: AWS (Redshift, Bedrock, S3, Glue, Lambda, Athena, DynamoDB, API Gateway, CloudWatch, EKS, ECS, EC2, RDS), Kubernetes, Docker, GitHub Actions CI/CD
- Principles: enterprise-grade patterns, performant async processing, high-availability reliability, strict ACID transactions, modular architecture.
"""

ABOUT_THIS_SITE = """\
- This portfolio is a hand-written static single-page app with no frontend framework — no React, Vue, Svelte, jQuery, Three.js or CSS preprocessor. It is vanilla ES modules and hand-authored CSS, with a static schematic backdrop painted entirely in CSS.
- Frontend: vanilla JavaScript ES modules, hand-written CSS, a service worker and Web App Manifest (installable PWA), DOMPurify and marked vendored from npm, and self-hosted subset fonts. No asset is loaded from a third-party origin.
- Frontend features: hash-routed sections, an interactive command prompt with a Ctrl+K palette, a live session-activity dashboard fed by server-sent events, this AI chat, a theme customizer, and a full account UI (register, login, TOTP 2FA, magic links, password reset, session management).
- Backend: FastAPI with Pydantic v2, SQLAlchemy 2 (async) over asyncpg, Alembic migrations, PostgreSQL, structlog, and an optional Kafka ingest pipeline that falls back to a simulator when no broker is configured.
- Auth: JWT (HS256) with refresh-token rotation, bcrypt, pyotp TOTP two-factor, magic links, and Have I Been Pwned range-API password screening.
- AI: this chat streams from Amazon Bedrock over server-sent events, with per-turn token and latency telemetry.
- Build and deploy: esbuild produces a bundled, minified, content-hashed dist/; GitHub Actions runs lint, tests and migration drift checks, then rsyncs to EC2 (Apache for the static tier, systemd + Uvicorn for the API) with automatic rollback.
- Side projects on the same domain: a Champions League bracket predictor at /ucl, a retired World Cup predictor at /worldcup, and an arcade at /arcade with 2048, Tetris, Flapper, Stack, Snake and Breaker — all written from scratch in vanilla JavaScript with no game engine.
"""
