// GENERATED by scripts/generate_resume.py from content/resume.json.
// Do not edit: `npm run check:resume` fails CI when this drifts.
//
// The Ctrl+K palette renders these alongside the command registry, so a
// visitor searching "Redshift" or "Kafka" lands on the section that says so.
// Find-in-page cannot do this job: the router only renders one section at a
// time, so the browser never has the other seven in the DOM to search.

export const CONTENT_INDEX = [
  {
    "section": "resume",
    "title": "Experience",
    "text": "Eight years at one company, across data platforms, OLTP and OLAP systems, and backend services. The full technology list is at the foot of this page.",
    "kind": "section"
  },
  {
    "section": "hobbies",
    "title": "Interests & Hobbies",
    "text": "What I do when I'm not building data pipelines — four habits that keep the other twelve hours honest.",
    "kind": "section"
  },
  {
    "section": "apps",
    "title": "Apps",
    "text": "Side projects that live on their own pages, away from the portfolio. Pick one — each opens in a new tab.",
    "kind": "section"
  },
  {
    "section": "activity",
    "title": "Session Activity",
    "text": "Everything this site has recorded about your visit, as it happens. It stays with your session — no third-party trackers, nothing that follows you off the page.",
    "kind": "section"
  },
  {
    "section": "resume",
    "anchor": "exp-data-engineering-modeling-olap",
    "title": "Data Engineering & Modeling (OLAP)",
    "text": "Architected multi-source ingestion pipelines using PySpark, Matillion, and Boomi (CDC, watermark extracts, SaaS APIs, flat files) into Amazon Redshift, decoupling batch and near-real-time streaming via Amazon SQS for automated staging, deduplication, cleansing, and SQL business transformations. Designed enterprise star and snowflake dimensional models, and developed LookML semantic models and Explores for core supply chain metrics (inventory turns, dock-to-stock cycle times, order fill rates, freight spend) with optimized datagroups and PDT lifecycle policies. Implemented reverse-ETL pipelines syncing curated data back into Salesforce and Zoho, and partnered with cross-functional stakeholders (Operations, Sales, Finance) to deliver executive Looker dashboards standardizing KPIs across departments.",
    "kind": "experience"
  },
  {
    "section": "resume",
    "anchor": "exp-backend-middleware",
    "title": "Backend & Middleware",
    "text": "Architected enterprise-grade serverless REST APIs and asynchronous order ingestion middleware using AWS API Gateway, Lambda, SQS FIFO, and Step Functions (Saga pattern), reliably fanning out multi-channel B2B/B2C orders to legacy ERP, WMS, and inventory distribution systems. Engineered a distributed DynamoDB caching layer with SHA-256 payload fingerprinting and native TTL eviction, cutting primary database load by 30–50%. Sustained 99.9% transaction completion through idempotent request handling, API Gateway throttling, DLQ redrive policies, exponential backoff, and circuit breakers. Developed a high-concurrency Available-to-Promise (ATP) inventory reservation microservice using atomic conditional writes and distributed locks to prevent overselling. Implemented a dual-engine search strategy combining Elasticsearch with SQL Server for sub-second search across millions of historical orders and invoices.",
    "kind": "experience"
  },
  {
    "section": "resume",
    "anchor": "exp-database-systems-oltp",
    "title": "Database Systems (OLTP)",
    "text": "Owned OLTP database architecture and administration running mission-critical order-to-cash operations across pricing, rebates, commissions, and ERP/WMS/TMS integration feeds. Architected the enterprise pricing engine in SQL Server, resolving sales-rep overrides, customer contract pricing, commodity pricing, COGS, and discount layers into real-time customer–item–DC prices via ACID-compliant T-SQL procedures. Scaled the pricing API to sustain 100,000–200,000 executions/min at sub-100 ms latency with zero deadlocks under heavy concurrent load. Modeled SCD Type 2 temporal pricing for point-in-time auditability, and engineered PriceIQ statistical pricing using IQR outlier fencing and skew-adjusted distribution analysis to intelligently price custom setups. Built the vendor rebate calculation platform, sales commission payroll, and WMS/TMS activity-based incentive payroll.",
    "kind": "experience"
  },
  {
    "section": "resume",
    "anchor": "exp-database-administration-reliability-oltp-olap",
    "title": "Database Administration & Reliability (OLTP & OLAP)",
    "text": "Eliminated high-frequency lock-conversion deadlocks, write skew, and reader–writer blocking across high-throughput OLTP workloads by pairing targeted locking hints (UPDLOCK, HOLDLOCK, ROWLOCK) with deterministic UPSERT ordering and tuning Read Committed Snapshot Isolation (RCSI). Resolved tempdb spills, parameter sniffing, and bookmark lookups through execution plan profiling, memory grant tuning, composite clustered/covering index redesigns, and table partitioning. Automated enterprise maintenance, index defragmentation, and statistics via Ola Hallengren on SQL Server Agent, administered Always On Availability Groups (HA/DR), and tuned CDC replication. Optimized Amazon Redshift storage architectures (KEY/ALL/EVEN distribution, sort keys, AZ64/ZSTD compression), WLM parameter queues, materialized views, PII data encryption, RBAC, and CloudWatch performance alarms.",
    "kind": "experience"
  },
  {
    "section": "resume",
    "anchor": "exp-cloud-architecture-modernization",
    "title": "Cloud Architecture & Modernization",
    "text": "Architected and provisioned an enterprise-scale, fault-tolerant AWS cloud foundation spanning multi-AZ VPCs, API Gateway, Lambda, Step Functions, SQS FIFO, DynamoDB, and Amazon Redshift. Deployed a secure, auto-scaled internal application tier on AWS (EC2 in multi-AZ VPCs, Auto Scaling, hardened security groups, Route 53, Apache HTTPD reverse proxies) with automated open-source TLS rotation. Engineered an event-driven Master Data Management (MDM) ecosystem across Zoho, establishing governed golden records for customer, item, and supplier entities with automated webhook and message-queued distribution to tier-1 ERP, WMS, and TMS systems to eliminate synchronization lag and discrepancies across warehouse fulfillment and freight routing networks.",
    "kind": "experience"
  },
  {
    "section": "resume",
    "anchor": "exp-devops-infrastructure",
    "title": "DevOps & Infrastructure",
    "text": "Established end-to-end operational reliability, automated maintenance, and proactive infrastructure observability across distributed cloud microservices and database clusters. Automated enterprise SQL Server maintenance, index defragmentation, and statistics updates using Ola Hallengren orchestrated via SQL Server Agent. Built robust monitoring and alerting in SolarWinds (waits, blocking, resource pressure) and AWS CloudWatch (disk spill, CPU utilization, concurrency metrics). Authored custom T-SQL health audit scripts, enforced least-privilege RBAC, and implemented resilient fault-tolerance mechanisms including automated Dead-Letter Queue (DLQ) redrives, exponential backoff, circuit breakers, and zero-downtime automated TLS certificate rotations.",
    "kind": "experience"
  },
  {
    "section": "resume",
    "anchor": "exp-generative-ai-web-applications",
    "title": "Generative AI & Web Applications",
    "text": "Integrated Google's Model Context Protocol (MCP) server in Looker, exposing curated semantic definitions, Explores, and supply chain KPIs to generative AI agents to enable natural-language-to-SQL querying and prompt-driven analytical dashboard generation. Engineered high-throughput, asynchronous FastAPI backend microservices with strict Pydantic schema validation, standardizing departmental custom data capture and preventing operational data corruption across downstream pipelines. Delivered responsive, high-performance web applications and internal portals featuring seamless API integrations and granular role-based access control.",
    "kind": "experience"
  },
  {
    "section": "resume",
    "title": "AWS technologies",
    "text": "Amazon Redshift, Amazon Bedrock, Amazon S3, AWS Glue, AWS Lambda, Amazon Athena, DynamoDB, API Gateway, CloudWatch, Amazon EKS, Amazon ECS, EC2, RDS, IAM, SNS, SQS, Glacier",
    "kind": "skills"
  },
  {
    "section": "resume",
    "title": "Data & Analytics technologies",
    "text": "Matillion, PySpark, Dell Boomi, Looker, Pandas, NumPy",
    "kind": "skills"
  },
  {
    "section": "resume",
    "title": "Databases & Messaging technologies",
    "text": "PostgreSQL, SQL Server, MySQL, Redis, Elasticsearch, Apache Kafka, RabbitMQ",
    "kind": "skills"
  },
  {
    "section": "resume",
    "title": "Backend & APIs technologies",
    "text": "FastAPI, Pydantic, SQLAlchemy, Alembic, boto3, Multiprocessing, Multithreading",
    "kind": "skills"
  },
  {
    "section": "resume",
    "title": "Languages technologies",
    "text": "Python, T-SQL, PL/pgSQL, SQL, Bash / Linux",
    "kind": "skills"
  },
  {
    "section": "resume",
    "title": "DevOps & Tooling technologies",
    "text": "Git, Docker, Terraform, Kubernetes, GitHub Actions CI/CD, Pytest",
    "kind": "skills"
  },
  {
    "section": "about",
    "title": "Cloud & Serverless",
    "text": "Amazon Redshift, Amazon Bedrock, S3, AWS Glue, Lambda, Athena, DynamoDB, EKS, ECS, RDS, CloudWatch",
    "kind": "skills"
  },
  {
    "section": "about",
    "title": "Backend & APIs",
    "text": "Python, FastAPI, boto3, SQLAlchemy (asyncpg), Pydantic, Multiprocessing, Multithreading",
    "kind": "skills"
  },
  {
    "section": "about",
    "title": "Data Engineering & BI",
    "text": "Matillion, PySpark, Looker, Pandas, NumPy",
    "kind": "skills"
  },
  {
    "section": "about",
    "title": "Databases & Middleware",
    "text": "PostgreSQL, SQL Server, Amazon Redshift, MySQL, Dell Boomi, Redis, Apache Kafka, RabbitMQ, Elasticsearch, Alembic",
    "kind": "skills"
  },
  {
    "section": "about",
    "title": "Languages & Scripting",
    "text": "Python, T-SQL, PL/pgSQL, SQL, Bash / Linux",
    "kind": "skills"
  },
  {
    "section": "about",
    "title": "DevOps & Tooling",
    "text": "Git, Docker, Terraform, Kubernetes, GitHub Actions CI/CD, Pytest",
    "kind": "skills"
  }
];
